### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Basilakis** [devinsays/edd-account-helpers#3]
Hello,

Is there any update to EED, cause the following code is giving back no output at all.

Thanks!

**Comment by devinsays** [comment]
Haven't tested recently, but everything is working for the two sites I run it with.

Are you getting any WP_DEBUG errors? How did you test/implement it?

**Comment by Basilakis** [comment]
Hey,

Thanks a lot for the quick reply.
I have activated the plugin and then used the sample code you provided but nothing to be outputed.
Is the license script need to get some output, or it can run without it also?

**Comment by devinsays** [comment]
Where are you using the code? On page template?

Does the user you are testing with have purchases assigned to it?

The basic code should work without the licensing extension. You may just need to var_dump some of the variables and debug a bit. This isn't really a supported project, just some code snippets I used that I thought could save some other developers time.

**Comment by Basilakis** [comment]
I am using on a page template, yes that is right!

Yes, there are 2 purchases on him, from 2 products. 
Debuging for 3 hours now to check what is wrong, so though to go ahead and ask.

I know that it is not a supported project, and thx a lot for the time you send to help me out.

**Comment by devinsays** [comment]
Here's how I would start debug. Maybe useful?

``` PHP

<?php echo 'testing correct template'; ?>

<?php if ( function_exists('edd_get_users_purchases') && function_exists('edd_account_get_user_downloads') ) :

    echo 'required functions available';

    // Set user as logged in user
    global $current_user;
    get_currentuserinfo();
    $downloads = edd_account_get_user_downloads( $current_user->ID, 'medium' );

    echo 'downloads:';
    var_dump( $downloads );
    echo '<br>';

    if ( $downloads ) : foreach ( $downloads as $download ) :
        echo 'download:'
        var_dump( $download );
        echo '<br>';
    endforeach; endif;

endif; ?>
```

You should always see the output "testing correct template".

If you don't see "required functions available", perhaps one of those functions is from the licensing extension.

**Comment by Basilakis** [comment]
Ok, seems I did the trick, the issue was the DL file link.

I will move it now a bit further, adding invoice link. 

Thx a TON for the usefull code :-)
